---
- name: build a container 
  hosts: localhost
  tasks:
    - name: stop current running container
      command: docker stop front-container 
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm front-container 
      ignore_errors: yes

    - name: remove front image
      command: docker rmi front-image
      ignore_errors: yes

    - name: build docker image using the dockerfile 
      command: docker build -t front-image . 
      
    - name: create front-container
      command: docker run -d -p 80:80 --name front-container front-image

    - name: Log in to Docker Hub
      command: docker login -u "elfatihyz" -p "zahira2000"
       
    - name: push front-image 
      command: docker tag front-image elfatihyz/dalli 
      
    - name: push elfatihyz/dalli
      command: docker push elfatihyz/dalli
